// <auto-generated />
using System;
using KabakalGym.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KabakalGym.API.Migrations
{
    [DbContext(typeof(KabakalDbContext))]
    [Migration("20260614085149_AddAiUsageTracker")]
    partial class AddAiUsageTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KabakalGym.API.Models.AiUsageTracker", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChatPromptsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChatWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RoutineWeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoutinesGeneratedThisWeek")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("AiUsageTrackers", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EquipmentStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Equipments_Status", "\"EquipmentStatus\" IN ('Available', 'Under Maintenance', 'Unavailable')");
                        });
                });

            modelBuilder.Entity("KabakalGym.API.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeExerciseName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MuscleGroup", "MovementType")
                        .HasDatabaseName("IX_Exercises_MuscleGroup_MovementType");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordResets_Token");

                    b.ToTable("PasswordResets", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.Routine", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoutineId");

                    b.HasIndex("UserId", "DateAssigned")
                        .HasDatabaseName("IX_Routines_UserId_DateAssigned");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.RoutineList", b =>
                {
                    b.Property<Guid>("RoutineListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sets")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StartingWeight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoutineListId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineLists", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.Subscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_Subscriptions_ExpirationDate");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_PaymentStatus", "\"PaymentStatus\" IN ('Paid', 'Unpaid', 'Pending')");
                        });
                });

            modelBuilder.Entity("KabakalGym.API.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("IX_Transactions_UserId_Timestamp");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_PaymentMethod", "\"PaymentMethod\" IN ('Cash', 'GCash', 'Card', 'QR-Code')");
                        });
                });

            modelBuilder.Entity("KabakalGym.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Admin', 'Member', 'Staff', 'GateKiosk')");
                        });
                });

            modelBuilder.Entity("KabakalGym.API.Models.Visit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("VisitId");

                    b.HasIndex("UserId", "CheckIn")
                        .HasDatabaseName("IX_Visits_UserId_CheckIn");

                    b.ToTable("Visits", (string)null);
                });

            modelBuilder.Entity("KabakalGym.API.Models.AiUsageTracker", b =>
                {
                    b.HasOne("KabakalGym.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("KabakalGym.API.Models.AiUsageTracker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Exercise", b =>
                {
                    b.HasOne("KabakalGym.API.Models.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Routine", b =>
                {
                    b.HasOne("KabakalGym.API.Models.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KabakalGym.API.Models.RoutineList", b =>
                {
                    b.HasOne("KabakalGym.API.Models.Exercise", "Exercise")
                        .WithMany("RoutineLists")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KabakalGym.API.Models.Routine", "Routine")
                        .WithMany("RoutineLists")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Subscription", b =>
                {
                    b.HasOne("KabakalGym.API.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("KabakalGym.API.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Transaction", b =>
                {
                    b.HasOne("KabakalGym.API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Visit", b =>
                {
                    b.HasOne("KabakalGym.API.Models.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Exercise", b =>
                {
                    b.Navigation("RoutineLists");
                });

            modelBuilder.Entity("KabakalGym.API.Models.Routine", b =>
                {
                    b.Navigation("RoutineLists");
                });

            modelBuilder.Entity("KabakalGym.API.Models.User", b =>
                {
                    b.Navigation("Routines");

                    b.Navigation("Subscription");

                    b.Navigation("Transactions");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
